---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "helm-ollama.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  MODEL: {{ .Values.configMap.model | quote }}
  BASE_URL: {{ .Values.configMap.baseUrl | quote }}