---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-ollama.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-ollama.labels" . | nindent 4 }}
type: Opaque
data:
  PINECONE_API_KEY: {{ .Values.secret.pineconeApiKey | b64enc }}
